# Generated by Django 2.0.1 on 2018-01-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='capital_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='figure_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='innovation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='market_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='article',
            name='engagement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='article',
            name='impression',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='article',
            name='sentiment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='total_capital_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='total_figure_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='total_innovation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='total_market_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='total_popularity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
